=== MGarcia-95/Actividad2_XML_DTD/02_DTD_Actividad2.dtd
<!ELEMENT biblioteca (libros, revistas, periodicos)>

<!-- LIBROS -->

<!ELEMENT libros (libro+)>
<!ELEMENT revistas (revista+)>
<!ELEMENT periodicos (periodico+)>


<!ELEMENT libro (titulo, capitulos, indice, sinopsis)>

<!-- defino los atributos de libro-->
    <!ATTLIST libro id ID CDATA #REQUIRED>
    <!ATTLIST libro tipo_clase (Novela | Infantil | Didactico) #REQUIRED>
    <!ATTLIST libro paginas CDATA #IMPLIED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (contenido)>
<!-- defino los atributos de capitulo-->
    <!ATTLIST capitulo titulo CDATA #REQUIRED>
    <!ATTLIST capitulo paginas CDATA #REQUIRED>

<!ELEMENT contenido (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>



<!-- REVISTAS -->

<!ELEMENT revista (titulo_r, numero_revista, indice, secciones+)>

<!-- Defino los atributos de revista-->

    <!ATTLIST revista id ID CDATA #REQUIRED>
    <!ATTLIST revista tipo_clase_r (Informatica | Corazon | Coches | Investigacion | Otras) #REQUIRED>
    <!ATTLIST revista paginas CDATA #IMPLED>

<!-- A continuacion se definen los elementos de revista con sus respectivos atibutos dentro de cada elemento --> 
<!ELEMENT titulo_r (#PCDATA)>
<!ELEMENT numero_revista (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT secciones (seccion_r+)>
<!ELEMENT seccion_r (contenido)>
    <!ATTLIST seccion_r paginas CDATA #IMPLED>
<!ELEMENT contenido (#PCDATA)> 


<!-- Periodicos: Tienen:
Elementos: periodico, secciones_p -> seccion_p, articulos -> articulo, contenido_p, indice_p
Atributos: ID, tipo_clase_p, fecha_publicacion, tipo_seccion_p, autor  -->

<!ELEMENT periodico (secciones_p, indice_p)>

    <!ATTLIST periodico id ID CDATA #REQUIRED>
    <!ATTLIST periodico tipo_clase_p (Nacional | Internacional) #REQUIRED>
    <!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>

<!ELEMENT secciones_p (seccion_p+)> 

<!ELEMENT seccion_p (articulos)>
    <!ATTLIST seccion_p tipo_seccion_p (Economica | Opinion | Deportes | Nacional | Internacional) #REQUIRED>
<!ELEMENT articulos (articulo+)>
<!ELEMENT articulo (contenido_p)>
    <!ATTLIST articulo autor CDATA #REQUIRED>
<!ELEMENT contenido_p (#PCDATA)>
<!ELEMENT indice_p (#PCDATA)>

<!-- Defino varias entidades -->

<!ENTITY AEP "Aprende a educar a un Pez">
<!ENTITY OT " El origen de Thanos">

=== MGarcia-95/Actividad2_XML_DTD/Actividad2_LMSGI.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "02_DTD_Actividad2.dtd" [
    <!ENTITY AEP "entity-value">
    <!ENTITY OT "entity-value">
<<<<<<< HEAD
]>
=======
    <!ENTITY MB "entity-value">
]>

<!-- En este caso añadimos tambien la posibilidad de probar el mismo documento con el xsd correspondiente -->
<!-- biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema" 
        xsi: noNamespaceSchemaLocation= "03_XSD_Actividad2.xsd" -->

>>>>>>> dacef49b65244b9b86d65066bc271522630c8c94
<biblioteca>
   <!-- Para los libros este atributo empieza con la letra “L” 
        seguido de 4 dígitos identificativos-->
        <!-- Los libros a su vez son clasificados en novela, infantil o didáctico -->
    <libros>

        <libro id="L-1234" tipo_clase="Didactico" paginas="23">
            <titulo>&AEP;</titulo>
            <capitulos>
                <capitulo titulo="Clases de peces" paginas="15">
                    <contenido>Hay muchos tipos de peces, si quieres saberlos todos compra una enciclopedia</contenido>
                </capitulo>

                <capitulo titulo="Como darles de comer" paginas="6">
                    <contenido>Si les das poco se moriran, si les das mucho, explotaran y moriran, dales lo justo.</contenido>
                </capitulo>

                <capitulo titulo="Enseña a tu pez a hacerse el muerto" paginas="8">
                    <contenido>Es una tarea compleja, pero el que la sigue la consigue, lorem ipsum.</contenido>
                </capitulo>
            </capitulos>
            <indice>Aqui va el indice</indice>
            <sinopsis>Aqui va la sinopsis</sinopsis>
        </libro>

<<<<<<< HEAD
        <libro id="L-5678" tipo_clase="Novela" paginas="46">
=======
        <libro id="L-5678" tipo_clase="Novela" paginas="90">
>>>>>>> dacef49b65244b9b86d65066bc271522630c8c94
            <titulo>&OT;</titulo>
            <capitulos>
                <capitulo titulo="Origen de Thanos" paginas="16">
                    <contenido>Thanos nacio siendo un niño gigante hipermusculado que pensaba que
                    sobraba gente en el universo</contenido>
                </capitulo>

                <capitulo titulo="Crecimiento de Thanos" paginas="34">
                    <contenido>Crecio en una familia donde no le querian y tambien queria acabar con la mitad de su familia
                    que les caia mal</contenido>
                </capitulo>

                <capitulo titulo="El motivo del odio de Thanos" paginas="45">
                    <contenido>Aqui empiezan a contarse los problemas mentales dee thanos para querer acabar 
                    con la mitad del universo</contenido>
                </capitulo>

                <capitulo titulo="Thanos esta aburrido" paginas="28">
                    <contenido>Tras aniquilar a la mitad de toda civilizacion, Thanos se va a una casita humilde a vivir placidamente
                    y comer frutitas sin pensar en lo que se le viene encima</contenido>
                </capitulo>

            </capitulos>
            <indice>Aqui va el indice</indice>
            <sinopsis>Aqui escribimos la sinopsis</sinopsis>
        </libro>

    </libros>

    <revistas>
<<<<<<< HEAD

        <revista id="R0001" tipo_clase="Investigacion" paginas="5">
=======
        <!-- En el caso de las revistas empieza por la letra “R”.-->
        <revista id="R0001" tipo_clase_r="Investigacion" paginas="5">
            <!-- informática, corazón, coches, investigación y otras-->
>>>>>>> dacef49b65244b9b86d65066bc271522630c8c94
            <titulo_r>Comer es vivir</titulo_r>
            <numero_revista>48</numero_revista>
            <indice>En este ejemplar explicaremos por qué tienes tanta hambre todos los dias</indice>
            <secciones>
                <seccion_r paginas="3">
                    <contenido>¿El hambre es mental o no? No, tienes hambre porque eres un ser vivo</contenido> 
                </seccion_r>
                <seccion_r paginas="2">
                    <contenido>La razón por la que comer es vivir es porque te nutres mientras disfrutas/vives. </contenido>
                </seccion_r>
            </secciones>
        </revista>

    </revistas>

    <!-- Para los periódicos este atributo empieza por la letra “P” 
        seguido de los 4 dígitos identificativos-->
       <!-- Los periódicos se clasifican en nacionales e internacionales-->

<<<<<<< HEAD
    <periodicos>

        <periodico id="P-2222" tipo_clase_p="Nacional" fecha_publicacion="12/05/2023">                 
=======
        <periodico id="P-2222" tipo_clase_p="Nacional" fecha_publicacion="12/05/2023">           
>>>>>>> dacef49b65244b9b86d65066bc271522630c8c94
            <secciones_p>
                <seccion_p tipo_seccion_p="Opinion">
                    
                    <articulos>
<<<<<<< HEAD
                        <articulo autor="Majin Boo">
                            <contenido_p>Majin boo es entrevistado y desvela porque es tan malvado</contenido_p>
=======
                        <articulo autor="&MB;">
                            <contenido_p>
                            <!-- necesita un atributo que referencie a la información-->
                            majin boo es entrevistado y desvela porque es tan malvado
                            </contenido_p>
>>>>>>> dacef49b65244b9b86d65066bc271522630c8c94
                        </articulo>
                    </articulos>
                </seccion_p>

                <seccion_p tipo_seccion_p="Internacional">
                    
                    <articulos>
                        <articulo autor="Jiren">
                            <contenido_p>
                            
                            Jiren cuenta como se convirtió en el guerrero mas fuerte de su universo
                            </contenido_p>
                        </articulo>
                    </articulos>
                </seccion_p>
            </secciones_p>
            <indice_p>Aqui va un indice</indice_p>
        </periodico>
        
    </periodicos>

</biblioteca>
